image:
  repository: acrazuredevopsbuildmg.azurecr.io/azure-devops-build-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

replicaCount: 2

canary:
  enabled: false
  replicaCount: 1
  image:
    tag: ""
    
resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 128Mi

probes:
  liveness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
  readiness:
    path: /
    initialDelaySeconds: 3
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

serviceAccount:
  create: true
  name: app-sa
  workloadIdentityClientId: ""

podLabels: {}

podAnnotations: {}

namespace: app

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}
tolerations: []
affinity: {}