apiVersion: v1
kind: Pod
metadata:
  name: kv-workload-identity-test
  namespace: app
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: app-sa
  containers:
    - name: test
      image: mcr.microsoft.com/azure-cli:latest
      command: ["sh", "-c"]
      args:
        - |
          az login --service-principal -u $AZURE_CLIENT_ID --tenant $AZURE_TENANT_ID --federated-token "$(cat $AZURE_FEDERATED_TOKEN_FILE)" &&
          az keyvault secret show --vault-name kv-azure-devops-build-mg --name workload-identity-test --query value -o tsv
  restartPolicy: Never